apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-calculator-app
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: advanced-calculato
  template:
    metadata:
      labels:
        app: advanced-calculator
    spec:
      containers:
      - name: node-app
        image: pasandocker123/advanced-calculator #  image name
        ports:
        - containerPort: 4000